import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const uiDir = path.dirname(fileURLToPath(import.meta.url));
const appSource = readFileSync(path.resolve(uiDir, 'App.tsx'), 'utf8');
const viewportSource = readFileSync(path.resolve(uiDir, 'Noclip3DViewport.tsx'), 'utf8');
const gobjSignatureBlock = viewportSource.slice(
  viewportSource.indexOf('function getGobjSignature'),
  viewportSource.indexOf('function buildSceneOverlayData'),
);
const sceneSource = readFileSync(
  path.resolve(uiDir, '../../vendor/noclip.website/src/MarioKartWii/Scenes_MarioKartWii.ts'),
  'utf8',
);

describe('editor ergonomics audit', () => {
  it('contains structural evidence for multi-select, batch edit, duplicate/delete, and hover/invalid highlighting', () => {
    expect(appSource).toContain("const [selectedIds, setSelectedIds] = useState<string[]>([])");
    expect(appSource).toContain('selectedEntities.length > 1');
    expect(appSource).toContain('BatchSelectionPanel');
    expect(appSource).toContain('Fill Between');
    expect(appSource).toContain("const [inspectorSection, setInspectorSection] = useState<InspectorSection>('object');");
    expect(appSource).toContain('Object Settings');
    expect(appSource).toContain('Track Settings');
    expect(appSource).toContain('Details');
    expect(appSource).toContain('DetailsSummaryBar');
    expect(appSource).toContain('detailsSectionHeader');
    expect(appSource).toContain('Route / Point Data');
    expect(appSource).toContain('Object Setup');
    expect(appSource).toContain('Route Binding');
    expect(appSource).toContain('Path Group');
    expect(appSource).toContain("selected.section === 'STGI' ? 'track' : 'object'");
    expect(appSource).toContain("{inspectorSection === 'object' ? (");
    expect(appSource).toContain('Post Effects');
    expect(appSource).toContain('Create Fog File');
    expect(appSource).toContain('posteffect/posteffect.bdof_demo');
    expect(appSource).toContain('Create Lighting File');
    expect(appSource).toContain('posteffect/posteffect.blight');
    expect(appSource).toContain('fillBetweenPreviewPositions');
    expect(appSource).toContain('copySelectedEntity');
    expect(appSource).toContain('duplicateSelectedEntity');
    expect(appSource).toContain('pasteClipboardEntity');
    expect(appSource).toContain('const transientViewportEditRef = useRef(false);');
    expect(appSource).toContain('const analysisTrack = transientViewportEditRef.current ? editSessionRef.current?.track ?? track : track;');
    expect(appSource).toContain('function applyTransientEditorChange(');
    expect(appSource).toContain('startTransition(updateState);');
    expect(appSource).toContain('materializeViewportInteractionTrack(before.track, after.track)');
    expect(appSource).toContain('previewMovedEntity(currentTrack, entity.id, position)');
    expect(appSource).toContain('previewRotatedEntity(currentTrack, entity.id, rotation)');
    expect(appSource).toContain("const isViewportCameraLookActive = () => document.documentElement.dataset.viewportCameraLook === 'active';");
    expect(appSource).toContain("if (event.key.toLowerCase() === 'w') {");
    expect(appSource).toContain("setTool('translate');");
    expect(appSource).toContain("if (event.key.toLowerCase() === 'e') {");
    expect(appSource).toContain("setTool('rotate');");
    expect(appSource).toContain("if (event.key.toLowerCase() === 'r') {");
    expect(appSource).toContain("setTool('scale');");
    expect(appSource).toContain("event.key.toLowerCase() === 'l'");
    expect(appSource).toContain("event.key === 'Delete' || event.key === 'Backspace'");
    expect(appSource).toContain('onDelete={deleteSelectedEntity}');
    expect(appSource).not.toContain('>Common<');
    expect(appSource).not.toContain('title="Translate"');
    expect(appSource).not.toContain('title="Rotate"');
    expect(appSource).not.toContain('title="Scale"');
    expect(appSource).not.toContain('title="Normal view"');
    expect(appSource).not.toContain('title="Collision dev view"');
    expect(appSource).not.toContain('title="Top-down view"');
    expect(appSource).not.toContain('title="Orthographic view"');
    expect(appSource).not.toContain('>Copy<');
    expect(appSource).not.toContain('>Duplicate<');
    expect(appSource).not.toContain('>Paste<');
    expect(appSource).toContain('className="button buttonIconOnly" disabled={historyState.undo === 0}');
    expect(appSource).toContain('className="button buttonIconOnly" disabled={historyState.redo === 0}');
    expect(appSource).toContain('if (visible && viewMode !== \'dev\') setViewMode(\'dev\');');
    expect(appSource).not.toContain('Snap selected to collision');
    expect(appSource).not.toContain('Snap to Surface');

    expect(viewportSource).toContain('marqueeSelection');
    expect(viewportSource).toContain('event.shiftKey');
    expect(viewportSource).toContain('event.ctrlKey');
    expect(viewportSource).toContain('isAdditiveSelectionModifier');
    expect(viewportSource).toContain('function isCollisionSnapModifier(event: { ctrlKey: boolean; metaKey: boolean }): boolean {');
    expect(viewportSource).toContain('onSelectMany?.(selectedIds, { additive: marquee.additive })');
    expect(viewportSource).toContain('const ENTITY_DRAG_START_THRESHOLD_PX = 4;');
    expect(viewportSource).toContain('pendingEntityDragRef');
    expect(viewportSource).toContain('topRightOverlay');
    expect(viewportSource).toContain('onChangeTool?: (tool: TransformTool) => void;');
    expect(viewportSource).toContain('onChangeViewMode?: (mode: ViewMode) => void;');
    expect(viewportSource).toContain('onChangeCollisionVisible?: (visible: boolean) => void;');
    expect(viewportSource).toContain('className="segmented viewportToolSegmented"');
    expect(viewportSource).toContain('className="viewportModeSelect"');
    expect(viewportSource).toContain('viewportTopRightStack');
    expect(viewportSource).toContain('fillBetweenPreview: SceneOverlayFillBetweenPreview[]');
    expect(viewportSource).toContain('routeDeviationSegments: SceneOverlayRouteDeviationSegment[]');
    expect(viewportSource).toContain('routeDeviationCaps: SceneOverlayRouteDeviationCap[]');
    expect(viewportSource).toContain('const [hoveredHandle, setHoveredHandle] = useState<GizmoHandleKey | null>(null)');
    expect(viewportSource).toContain('const [previewTransform, setPreviewTransform] = useState<EntityTransformPreview | null>(null)');
    expect(viewportSource).toContain('const routeVisibilityRef = useRef<Record<RouteVisibilityKey, boolean>>({');
    expect(viewportSource).toContain('const interactionCommitFrameRef = useRef<number | null>(null);');
    expect(viewportSource).toContain('function scheduleInteractionCommit(pending: PendingInteractionCommit) {');
    expect(viewportSource).toContain('function flushPendingInteractionCommit() {');
    expect(viewportSource).toContain('const deltaDegrees = -normalizeAngle(angle - drag.startAngle) * (180 / Math.PI);');
    expect(viewportSource).toContain('if (selectedIdRef.current && hasCameraPositionChanged(cameraPosition, overlayCameraPositionRef.current)) {');
    expect(viewportSource).toContain('const baseLength = Math.max(180, Math.min(900, scaleLength || 260));');
    expect(viewportSource).toContain('const distanceLength = Math.max(30, distance * 0.08);');
    expect(viewportSource).toContain('function applyFPSCameraFrame(controller: FPSCameraController, frame: CameraFrame) {');
    expect(viewportSource).toContain('mat4.targetTo(camera.worldMatrix, frame.eye, frame.target, CAMERA_WORLD_UP);');
    expect(viewportSource).toContain('controller.cameraUpdateForced();');
    expect(viewportSource).toContain('controller.update(viewer.inputManager, 0, 0);');
    expect(viewportSource).toContain("const CAMERA_MOVE_KEYS = ['KeyW', 'KeyA', 'KeyS', 'KeyD'");
    expect(viewportSource).toContain("document.documentElement.dataset.viewportCameraLook = active ? 'active' : 'inactive';");
    expect(viewportSource).toContain('const restoreSuppressedKeys = withSuppressedCameraMovementKeys(result.viewer!);');
    expect(viewportSource).toContain('updateActiveDrag(event.clientX, event.clientY, isCollisionSnapModifier(event));');
    expect(viewportSource).toContain('const position = placeFromScreen(event.clientX, event.clientY, 0, isCollisionSnapModifier(event));');
    expect(viewportSource).toContain('getVisibleEntitiesForRouteFilter(track.kmp.entities, routeVisibilityRef.current, track.kmp, routeUsage)');
    expect(viewportSource).toContain('routeVisibilityRef.current,');
    expect(viewportSource).toContain('const MAX_CAMERA_LOOK_DELTA_PX = 240;');
    expect(viewportSource).toContain('document.addEventListener(\'pointerlockchange\', handlePointerLockChange);');
    expect(viewportSource).toContain('if (cameraLook.skipNextDelta || cameraLook.pointerLocked !== pointerLocked) {');
    expect(viewportSource).toContain('Math.abs(dx) > MAX_CAMERA_LOOK_DELTA_PX || Math.abs(dy) > MAX_CAMERA_LOOK_DELTA_PX');
    expect(viewportSource).toContain("scheduleInteractionCommit({ kind: 'moveEntity', entity, position });");
    expect(viewportSource).toContain('flushPendingInteractionCommit();');
    expect(viewportSource).toContain('setDragPreview({ id: entity.id, position, rotation: entity.rotation, scale: entity.scale });');
    expect(viewportSource).toContain('rotation: startEntity.rotation');
    expect(viewportSource).toContain("const selectedDeviationSections = new Set<'ENPT' | 'ITPT'>();");
    expect(viewportSource).toContain('buildRouteDeviationSegment(');
    expect(viewportSource).toContain('const radiusA = Math.max(0, (a.pointDeviation ?? 0) * 50);');
    expect(viewportSource).toContain('aLeft: { x: positionA.x + offsetX * radiusA, y: positionA.y, z: positionA.z + offsetZ * radiusA },');
    expect(viewportSource).toContain("specialColor?: 'bulletBillCantStop';");
    expect(viewportSource).toContain("entity.section === 'ITPT' && (entity.pointSettings?.[1] === 1 || entity.pointSettings?.[1] === 0x0b)");
    expect(viewportSource).toContain("id: `${entity.id}-cap`,");
    expect(viewportSource).toContain('radius: Math.max(0, (entity.pointDeviation ?? 0) * 50),');
    expect(viewportSource).not.toContain('disabled={viewMode !== \'dev\'}');
    expect(gobjSignatureBlock).toContain('entity.routeIndex ?? -1,');
    expect(gobjSignatureBlock).not.toContain('entity.position.x,');
    expect(gobjSignatureBlock).not.toContain('entity.rotation?.x ?? 0,');
    expect(gobjSignatureBlock).not.toContain('entity.scale?.x ?? 1,');
    expect(viewportSource).toContain('}, [gobjSignature]);');
    expect(viewportSource).not.toContain('}, [gobjSignature, track?.kmp]);');
    expect(viewportSource).toContain('setHoveredId');
    expect(viewportSource).toContain('invalid:');

    expect(sceneSource).toContain('class EditorStartPreviewRenderer implements BaseObject');
    expect(sceneSource).toContain('PreviewDummies.u8');
    expect(sceneSource).toContain('previewDummyDriverAssetPath');
    expect(sceneSource).toContain('previewDummyKartAssetPath');
    expect(sceneSource).toContain('editorOverlayData.fillBetweenPreview');
    expect(sceneSource).toContain('routeDeviationSegments: EditorOverlayRouteDeviationSegment[]');
    expect(sceneSource).toContain('routeDeviationCaps: EditorOverlayRouteDeviationCap[]');
    expect(sceneSource).toContain('private drawEditorRouteDeviationSegment(segment: EditorOverlayRouteDeviationSegment): void');
    expect(sceneSource).toContain('debugDraw.drawTriSolidP(aLeft, bLeft, bRight, fillColor, editorOverlayPointOptions);');
    expect(sceneSource).toContain('private drawEditorRouteDeviationCap(cap: EditorOverlayRouteDeviationCap): void');
    expect(sceneSource).toContain('drawDiscSolidRU(center, editorOverlayFlatDiscRight, editorOverlayFlatDiscUp, radius, fillColor, 36, editorOverlayPointOptions);');
    expect(sceneSource).toContain("specialColor?: 'bulletBillCantStop';");
    expect(sceneSource).toContain('const editorOverlayBulletBillCantStopColor = colorNewFromRGBA(1.0, 0.32, 0.32, 0.98);');
    expect(sceneSource).toContain('centerHandle: EditorOverlayCenterHandle | null;');
    expect(sceneSource).toContain('private drawEditorArrowHead(');
    expect(sceneSource).toContain('private getEditorGizmoMetrics(length: number, active: boolean, hovered: boolean):');
    expect(sceneSource).toContain('private drawEditorRotateHandle(axis: EditorOverlayAxis): void');
    expect(sceneSource).toContain('private drawEditorLinearHandle(axis: EditorOverlayAxis, tool: \'translate\' | \'scale\'): void');
    expect(sceneSource).not.toContain('private drawEditorAxisLabel(');
    expect(sceneSource).not.toContain('plane.plane.toUpperCase()');
    expect(sceneSource).toContain('const kartModelNames = kartRRES.mdl0.map');
    expect(sceneSource).toContain('public kartInstances: MDL0ModelInstance[]');
    expect(sceneSource).toContain('selected: boolean;');
    expect(sceneSource).toContain('hovered: boolean;');
    expect(sceneSource).toContain('invalid: boolean;');
  });
});
